# Application
spring.application.name=${SPRING_APPLICATION_NAME:package-tracking-system}
server.port=8080

# PostgreSQL Database (usa variables de entorno)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/flypass}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:username}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000

# JPA/Hibernate
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Logging
logging.level.com.quind=${LOGGING_LEVEL_COM_QUIND:DEBUG}
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=package-tracking-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.max-poll-records=10
spring.kafka.consumer.fetch-min-size=1
spring.kafka.consumer.fetch-max-wait=500ms

spring.kafka.listener.ack-mode=manual
spring.kafka.listener.concurrency=3
spring.kafka.listener.poll-timeout=3000

retryconfig.topics.package-status=package-status-events
retryconfig.retry.maxRetryAttempts=3
retryconfig.retry.autoCreateRetryTopics=true
retryconfig.retry.retryIntervalMilliseconds=2000
retryconfig.retry.retryBackoffMultiplier=2.0
retryconfig.retry.maxRetryDurationMilliseconds=30000
retryconfig.dlt.enabled=true
retryconfig.dlt.topic-suffix=.packages.DLT

logging.level.org.apache.kafka=WARN
logging.level.org.springframework.kafka=INFO
logging.level.com.quind.infrastructure.kafka=DEBUG

