# Application
spring.application.name=${SPRING_APPLICATION_NAME:package-tracking-system}
server.port=8080

# PostgreSQL Database (usa variables de entorno)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/flypass}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:username}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000

# JPA/Hibernate
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Logging
logging.level.com.quind=${LOGGING_LEVEL_COM_QUIND:DEBUG}
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
